config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
	mount Sidekiq::Web => '/sidekiq' if Rails.env.development?
	mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.htmlz
	root to: 'home#index'

	resource :timeline, only: %i(show)

	resources :accounts, only: %i(show) do
		resources :follows, only: %i(create)
		resources :unfollows, only: %i(create)
		member do
			get :followings, :followers
		end
	end

	resource :profile, only: %i(show edit update)

	resources :posts do
		resource :like, only: %i(show create destroy)

		resources :comments, only: %i(index new create)
	end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :post
	belongs_to :user
	validates :content, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user
	belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
	validates :title, presence: true
	validates :content, presence: true
	validates :content, uniqueness: true


	belongs_to :user

	has_many_attached :images
	has_many :likes, dependent: :destroy
	has_many :comments, dependent: :destroy
end

app/models/profile.rb
class Profile < ApplicationRecord
	belongs_to :user
	has_one_attached :avatar
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :follower, class_name: 'User'
	belongs_to :following, class_name: 'User'

	after_create :send_email

	private
	def send_email
		RelationshipMailer.new_follower(following, follower).deliver_later
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

	validates :account, presence: true, length: { minimum: 2 }


	has_many :posts, dependent: :destroy
	has_many :likes, dependent: :destroy

	has_many :following_relationships, foreign_key: 'follower_id', class_name: 'Relationship', dependent: :destroy
	has_many :followings, through: :following_relationships, source: :following

	has_many :follower_relationships, foreign_key: 'following_id', class_name: 'Relationship', dependent: :destroy
	has_many :followers, through: :follower_relationships, source: :follower

	has_many :comments, dependent: :destroy
	has_one :profile, dependent: :destroy

	def has_written?(post)
		posts.exists?(id: post.id)
	end

	def has_liked?(post)
		likes.exists?(post_id: post.id)
	end

	def prepare_profile
		profile || build_profile
	end

	def follow!(user)
		user_id = get_user_id(user)
		following_relationships.create!(following_id: user_id)
	end

	def unfollow!(user)
		user_id = get_user_id(user)
		relation = following_relationships.find_by!(following_id: user_id)
		relation.destroy!
	end

	def has_followed?(user)
		following_relationships.exists?(following_id: user.id)
	end

	def avatar_image
		if profile&.avatar&.attached?
			profile.avatar
		else
			'default-avatar.png'
		end
	end

	private
	def get_user_id(user)
		if user.is_a?(User)
			user.id
		else
			user
		end
	end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_user, only: [:followings, :followers]

  def show
    @user = User.find(params[:id])
    if @user == current_user
      redirect_to profile_path
    end

		to = Time.current.at_end_of_day
    from = (to - 6.day).at_beginning_of_day


		user_ids = @user.followings.pluck(:id)
		@posts = Post.where(user_id: user_ids, created_at: from...to).left_joins(:likes).group(:id).order('count(likes.id) DESC').limit(5)
  end

  def followings
    @users = @user.followings
  end

  def followers
    @users = @user.followers
  end

  private
  def set_user
    @user = User.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

	def after_sign_in_path_for(resource)
		if current_user.profile.present?
			root_path
		else
			edit_profile_path
		end
	end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:account])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!

	def index
		post = Post.includes(:user).find(params[:post_id])
		comments = post.comments.includes(:user).all

		render json: comments
	end


	def new
		post = Post.find(params[:post_id])
		@comment = post.comments.build
	end

	def create
		post = Post.find(params[:post_id])
		@comment = post.comments.build(comment_params)
		@comment.save!

		render json: @comment
	end


	private
	def comment_params
		params.require(:comment).permit(:content).merge(user_id: current_user.id, post_id: params[:post_id])
	end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
	before_action :authenticate_user!

	def create
		current_user.follow!(params[:account_id])
		redirect_to account_path(params[:account_id])
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
	before_action :authenticate_user!

	def show
		post = Post.find(params[:post_id])
		like_status = current_user.has_liked?(post)
		render json: { hasLiked: like_status }
	end

	def create
		post = Post.find(params[:post_id])
		post.likes.create!(user_id: current_user.id)

		render json: { status: 'ok' }
	end

	def destroy
		post = Post.find(params[:post_id])
		like = post.likes.find_by!(user_id: current_user.id)
		like.destroy!

		render json: { status: 'ok' }
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :set_post, only: [:show]
	before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

	def index
		@posts = Post.all
	end

	def show
		# @post =Post.includes(:user).find(params[:id])
		# @comments = @post.comments.includes(:user).all
		# @comment = @post.comments.build(user_id: current_user.id) if current_user
	end

	def new
		@post = current_user.posts.build
	end

	def create
		@post = current_user.posts.build(post_params)
		if @post.save
			redirect_to post_path(@post), notice: '保存できました'
		else
			flash.now[:error] = '保存に失敗しました'
			render :new
		end
	end

	def edit
		@post = current_user.posts.find(params[:id])
	end

	def update
		@post = current_user.posts.find(params[:id])
		if @post.update(post_params)
			redirect_to post_path(@post), notice: '更新できました'
		else
			flash.now[:error] = '更新できませんでした'
			render :edit
		end
	end

	def destroy
		post = current_user.posts.find(params[:id])
		post.destroy!
		redirect_to posts_path, notice: '削除に成功しました'
	end

	private
	def post_params
		params.require(:post).permit(:title, :content, :image, images: [])
	end

	def set_post
		@post = Post.find(params[:id])
	end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	before_action :authenticate_user!

	def show
		@profile = current_user.profile

		to = Time.current.at_end_of_day
    from = (to - 6.day).at_beginning_of_day

		user_ids = current_user.followings.pluck(:id)
		@posts = Post.where(user_id: user_ids, created_at: from...to).left_joins(:likes).group(:id).order('count(likes.id) DESC').limit(5)
	end

	def edit
		@profile = current_user.prepare_profile
	end

	def update
		@profile = current_user.prepare_profile
		@profile.assign_attributes(profile_params)
		if @profile.save
			redirect_to profile_path, notice: 'プロフィール更新できました!'
		else
			flash.now[:error] = '更新できませんでした'
			render :edit
		end
	end

	private
	def profile_params
		params.require(:profile).permit(
			:account,
			:avatar
		)
	end
end

app/controllers/timelines_controller.rb
class TimelinesController < ApplicationController
	before_action :authenticate_user!

	def show
		to = Time.current.at_end_of_day
    from = (to - 1.day).at_beginning_of_day

		user_ids = current_user.followings.pluck(:id)
		@posts = Post.where(user_id: user_ids, created_at: from...to).left_joins(:likes).group(:id).order('count(likes.id) DESC').limit(5)
	end
end

app/controllers/unfollows_controller.rb
class UnfollowsController <  ApplicationController
	before_action :authenticate_user!

	def create
		current_user.unfollow!(params[:account_id])
		redirect_to account_path(params[:account_id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/followers.html.haml
.container
	%header.header
		.header_icon
			- if !current_page?(root_path)
				= link_to :back do
					= image_tag 'arrow.svg', class: 'header_back'
			.header_title
				= link_to 'Followers', root_path
= render 'commons/follow', users: @users

app/views/accounts/followings.html.haml
.container
	%header.header
		.header_icon
			- if !current_page?(root_path)
				= link_to :back do
					= image_tag 'arrow.svg', class: 'header_back'
			.header_title
				= link_to 'Followings', root_path
= render 'commons/follow', users: @users

app/views/accounts/show.html.haml
= render 'commons/profile', user: @user

app/views/comments/new.html.haml
%ul
	- @comment.errors.full_messages.each do |message|
		%li= message

= form_with(model: @comment, url: post_comments_path(@comment.post), local: ture) do |f|
	%div
		= f.text_area :content
	= f.submit 'preservation', class: 'btn-secondary'

app/views/commons/_follow.html.haml
- users.each do |user|
	.post
		.post_form.follow_items
			= image_tag user.avatar_image
			%div
				%p= user.account

app/views/commons/_profile.html.haml
.container
	%header.header
		.header_icon
			- if !current_page?(root_path)
				= link_to :back do
					= image_tag 'arrow.svg', class: 'header_back'
			.user_account
				= user.account
			.user_content
				- if user == current_user
					= link_to 'Edit', edit_profile_path
				- else
					-if current_user&.has_followed?(user)
						= link_to 'Unfollow', account_unfollows_path(user), data: { method: 'post' }
					- else
						= link_to 'Follow', account_follows_path(user), data: { method: 'post' }
	.profile_icon
		= image_tag user.avatar_image
.count_content
	= link_to posts_path do
		.count_items
			.count_text
				= user.posts.count
			%p= 'Posts'
	= link_to followers_account_path(user) do
		.count_items
			.count_text
				= user.followers.count
			%p= 'Followers'
	= link_to followings_account_path(user) do
		.count_items
			.count_text
				= user.followings.count
			%p= 'Following'
.container
	= render 'timelines/show', posts: @posts

app/views/home/index.html.haml
.home_image
	= image_tag 'Rectangle.png'
	.home_title
		%h2= 'Social-app'
.container
	.link_content.btn-primary
		= link_to '投稿一覧を見る', posts_path
	.link_content.btn-primary
		= link_to 'プロフィールを確認する', profile_path

app/views/layouts/application.html.haml
!!!
%html
	%head
		%meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
		%title SocialMApp
		= csrf_meta_tags
		= csp_meta_tag
		= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
		= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
		%meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
	%body
		%p.notice= notice
		%p.alert= alert
		-# - if user_signed_in?
		-# 	= link_to 'log out', destroy_user_session_path, data: { method: 'delete' }
		= yield

app/views/posts/_form.html.haml
.container
	%header.header
		.header_icon.header_text
			- if !current_page?(root_path)
				= link_to 'Cance', :back, class: 'text_link'
				.header_title
					= link_to 'Status', root_path
				= link_to 'Post', posts_path, class: 'text_link'
		.post
			.post_form
				= image_tag post.user.avatar_image
				%div
					%p= post.user.account
	%ul
		- post.errors.full_messages.each do |message|
			%li= message
	= form_with(model: post, local: true) do |f|
		%div
			= f.label :images, 'Img'
		%div
			= f.file_field :images, multiple: true
		%div
			= f.label :title, 'Title'
		%div
			= f.text_field :title, class: 'text', placeholder:"What's on your mind ?"
		%div
			= f.label :content, 'Content'
		%div
			= f.text_area :content
		= f.submit 'preservation', class: 'btn-primary'

app/views/posts/edit.html.haml
= render 'form', post: @post

app/views/posts/index.html.haml
.container
	%header.header
		.header_icon
			- if !current_page?(root_path)
				= link_to new_post_path do
					= image_tag 'photo-camera.svg', class: 'header_back'
	- @posts.each do |post|
		.post
			.post_detail
				= link_to account_path(post.user) do
					= image_tag post.user.avatar_image
				%div
					.post_name
						= post.user.account
					.post_time
						= time_ago_in_words(post.created_at)
			.post_content
				- if post.images.attached?
					- post.images.each do |image|
						.post_image
							= image_tag(image)
			.post_content_item
				.post_like.active-like
					= link_to post_path(post) do
						= image_tag 'like-active.svg'
					%span= post.likes.count
				.post_group
					= link_to post_path(post) do
						= image_tag 'Group.svg'
				.post_share
					= link_to (image_tag 'share.svg'), 'https://twitter.com/i/flow/login'
			.post_title
				%p= post.title
				%p= post.content

app/views/posts/new.html.haml
= render 'form', post: @post

app/views/posts/show.html.haml
.container#post-show{data: {post_id: @post.id}}
	%header.header
		.header_icon
			- if !current_page?(root_path)
				= link_to new_post_path do
					= image_tag 'photo-camera.svg', class: 'header_back'
		.post
			.post_detail
				= link_to account_path(@post.user) do
					= image_tag @post.user.avatar_image
				%div
					.post_name
						= @post.user.account
					%p= time_ago_in_words(@post.created_at)
			.post_content
				- if @post.images.attached?
					- @post.images.each do |image|
						.post_image
							= image_tag(image)
			.post_content_item
				- if user_signed_in?
					.post_like.hidden.active-like
						= image_tag 'like-active.svg'
					.post_like.hidden.inactive-like
						= image_tag 'like.svg'
					.post_group
						= image_tag 'Group.svg'
					.post_share
						= link_to (image_tag 'share.svg'), 'https://twitter.com/i/flow/login'
			.post_title
				%p= @post.title
				%p= @post.content
.container
	%header.header
		.header_icon
			.header_title
				%h2 Comment
	.comments_container
- if user_signed_in?
	.form_container
		.comment_text_area.show_comment_form
			=	image_tag 'Group.svg', class: 'sm'
		.comment_text_area_after.hidden
			=	text_area_tag :comment_box, '', class: 'sm'
			.btn-secondary.add-comment-button
				コメントを追加

= javascript_pack_tag 'post'

app/views/profiles/edit.html.haml
.container
	%header.header
	.header_icon
		- if !current_page?(root_path)
			= link_to :back do
				= image_tag 'arrow.svg', class: 'header_back'
	%ul
		- @profile.errors.full_messages.each do |message|
			%li= message

	= form_with(model: @profile, url: profile_path, method: 'put', local: true) do |f|
		%div
			= f.label :avatar, 'Avatar'
		%div
			= f.file_field :avatar
		%div
			= f.label :account, 'Account', class: 'text-label'
		%div
			= f.text_field :account, class: 'text'

		= f.submit 'preservation', class: 'btn-primary'

app/views/profiles/show.html.haml
= render 'commons/profile', user: current_user

app/views/timelines/_show.html.haml
- posts.each do |post|
	.post
		.post_content
			- if post.images.attached?
				- post.images.each do |image|
					.post_image
						= image_tag(image)